---
- name: Join Kubernetes worker nodes
  hosts: workers
  become: true

  tasks:

    - name: Check if worker is already joined to Kubernetes
      ansible.builtin.stat:
        path: /etc/kubernetes/kubelet.conf
      register: kubelet_conf

    - name: Get Kubernetes join command from control plane
      ansible.builtin.command: kubeadm token create --print-join-command
      delegate_to: "{{ control_plane_host }}"
      register: join_command
      changed_when: false

    - name: Join worker nodes
      ansible.builtin.command: "{{ join_command.stdout }}"
      when: not kubelet_conf.stat.exists